pipeline {
    agent any

    environment {
        SONAR_SERVER = 'SonarQube'
        AUTH_SECRET = credentials('assets-auth-secret')
        CRON_SECRET = credentials('assets-cron-secret')
        AUTH_SELF_HOST_PASSWORD = credentials('assets-auth-self-host-password')
        DATABASE_URL = 'postgresql://postgres:postgres@db:5432/asset_app?sslmode=disable'
    }

    tools {
        nodejs 'NodeJS-24'
    }

    stages {

        stage('1. Build') {
            steps {
                checkout scm

                sh '''
                    set -e
                    corepack enable
                    corepack prepare pnpm@11.6.0 --activate
                    pnpm install --frozen-lockfile
                    pnpm build
                '''
            }
        }

        stage('2. Tests') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    sh 'pnpm test:unit'
                }
            }
        }

        stage('3. SonarQube') {
            steps {
                script {
                    def scannerHome = tool 'sonar-scanner'

                    withSonarQubeEnv("${SONAR_SERVER}") {
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=assets-tracker \
                            -Dsonar.sources=src \
                            -Dsonar.exclusions=node_modules/**,.next/**,coverage/** \
                            -Dsonar.typescript.tsconfigPath=tsconfig.sonar.json
                        """
                    }
                }

                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('4. Scan des Dépendances') {
            steps {
                sh 'pnpm audit --audit-level=high'
            }
        }

        stage('5. Pré-production') {
            steps {
                echo 'Déploiement en Pré-Production sur le port 8081.'
            }
        }

        stage('6. Validation & Notifications') {
            steps {
                input(
                    message: 'Valider le passage en Production ?',
                    ok: 'Approuver'
                )
            }
        }

        stage('7. Déploiement') {
            steps {
                sh 'docker compose up -d'
            }
        }
    }

    post {
        failure {
            mail(
                to: 'bouraadaoumaima11@gmail.com',
                subject: "ALERT: Échec du Pipeline ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: """Une erreur est survenue dans le pipeline.

Job : ${env.JOB_NAME}
Build : #${env.BUILD_NUMBER}

Logs :
${env.BUILD_URL}console
"""
            )
        }

        success {
            echo "Pipeline exécutée avec succès jusqu'à la Production."
        }
        
    }
}

// update jenkinsfile
